@startuml
Class Player{
    velocite: double
}

class Position{
x : int
y : int
}

Interface GameMode{
Action()
gravite : int
sprite : Sprite
hitboxe : Hitbox
}
Class Cube extends GameMode
Class UFO extends GameMode
Class Wheel extends GameMode

Class Level{
progression : Int
name : String
numberDeath : Int
music : AudioFile
layout : LayoutFile
score: Int
}

Enum Difficulty{
    easy
    medium
    hard
}


Interface Terrain{
size : Int
hitboxe : Hitbox
sprite : Sprite
bloodOpacity : int
Effect()
}

Interface Hitboxes{
color : Color

}

Class PadHitbox extends Hitboxes
Class BlockHitbox extends Hitboxes
Class SpikeHitbox extends Hitboxes
Class Spike extends Terrain
Class Block extends Terrain
Class Orb extends Terrain
Class Pad extends Terrain

Player "0.1" -- "0.1" GameMode
Player "0.1" -- "0.1" Position
Terrain "0.1" -- "0.1" Position
Terrain "1" -- "1" Hitboxes
Level "0.1" -- "0.n" Terrain
Level "0.1" -- "0.1" Player
Level "0.n" -- "1" Difficulty
@enduml
